FROM node:20-alpine


WORKDIR /app

# ==== Install Dependencies ====
COPY backend/package*.json ./backend/
RUN cd backend && npm install

COPY backend ./backend


EXPOSE 4000 8080 6379

CMD ["node","backend/src/index.js"]